folderin: /home/user/seminar2/test
folderout: /home/user/seminar2/out
folderext: /home/user/seminar2/folder1
username1: tests/p7zip-full.deb
username2: /home/user2/p7zip-full.deb
address: "0.0.0.0"
passwordssh: "11"
port: "22"
user: "user2"
